name: isportal
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.4.0
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.4.0
  reactive_forms: ^15.0.0
  mask_text_input_formatter: ^2.4.0
  reactive_pinput: ^1.0.0
  get_it: ^7.6.0
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  http: ^1.0.0
  js: ^0.6.7
  intl: ^0.18.1
  uuid: ^3.0.7
  localstorage: ^4.0.1+2
  shared_preferences: ^2.1.1
  reactive_flutter_typeahead: ^1.0.0
  reactive_file_picker: ^1.0.0
  percent_indicator: ^4.2.3
  collection: ^1.17.1
  flutter_html: ^3.0.0-beta.2
  simple_html_css: ^4.0.0
  reactive_advanced_switch: ^1.0.0
  json_annotation: ^4.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.1.1
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  build_runner: ^2.4.5


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/png/
    - assets/images/svg/
    

  fonts:
    - family: RedHatDisplay
      fonts:
        - asset: assets/fonts/redhatdisplay.ttf
    - family: RedHatDisplayItalic
      fonts:
        - asset: assets/fonts/redhatdisplayitalic.ttf
    - family: RedHatDisplay-ExtraBold
      fonts:
        - asset: assets/fonts/RedHatDisplay-ExtraBold.ttf
    - family: RedHatDisplay-Bold.ttf
      fonts:
        - asset: assets/fonts/RedHatDisplay-Bold.ttf

 